### ISSUE TITLE
Update-Personal-Website

### ISSUE THREAD

**Issue by kartikagarwal9** [kartikagarwal9/kartikagarwal9.github.io#1]
If you think you can edit and make it more better and functioning, you are most welcome.

**Comment by rperry99** [comment]
Hey There!

You have an awesome looking page so far!

I noticed under your virtual internships, you have them numbered as well as in an unordered list. Was that intentional? If not, I can fix that for you. 

![image](https://user-images.githubusercontent.com/24259120/95251693-e8d54f00-07e9-11eb-8222-9ac3ff74fc2b.png)

Also, your instagram and twitter links don't work at the bottom. Twitter just takes you to the twitter landing page and for instagram, it says the user doesn't exist. 

Let me know if you want these taken care of 🙂

**Comment by kartikagarwal9** [comment]
Yeah Great, Can you remove the bulletin from every column and instead of it write numbers like in the screenshot? And I will provide all the valid links for social media handles @rperry99

**Comment by kartikagarwal9** [comment]
https://www.facebook.com/kartikagarwal07/
https://twitter.com/kartikagarwal07
https://www.instagram.com/kartik_agarwal99/
https://www.linkedin.com/in/kartikagarwal99/

**Comment by rperry99** [comment]
Sure, no problem! I will get this updated for you!

**Comment by kartikagarwal9** [comment]
If anyone can make The Contact Form functioning can Apply, I will assign

**Comment by mdoutreluingne** [comment]
Hi @kartikagarwal9 , can I help you make the contact form, which I would do in PHP.

Can you assign this task to me please?

**Comment by kartikagarwal9** [comment]
Yeah Sure , Go Ahead @mdoutreluingne

**Comment by kartikagarwal9** [comment]
Hey the contact form you submitted @mdoutreluingne it was perfect , I wanted to know , I just needed to change my mail address only or something else too ?

**Comment by mdoutreluingne** [comment]
Thanks @kartikagarwal9, you have to put your email in the variable $ to and can be configure the mail server according to your host.

**Comment by kartikagarwal9** [comment]
Yeah i did that @mdoutreluingne , but the website isn't working as it requires index.html file , how can I resolve that issue ?

**Comment by mdoutreluingne** [comment]
@kartikagarwal9 Where is your website hosted?

**Comment by kartikagarwal9** [comment]
kartikagarwal9.github.io @mdoutreluingne

**Comment by mdoutreluingne** [comment]
Oh okay, I thought it was another web host seen that you put the "php" label on. The herbegemtent github service unfortunately does not support php : https://github.community/t/deploying-php-to-github-pages-is-it-possible/10288/3.

I will try to do it in JavaScript @kartikagarwal9

**Comment by kartikagarwal9** [comment]
ok thanks , i didn't know it @mdoutreluingne

**Comment by kartikagarwal9** [comment]
till then i am keeping it merged , if you can please contribute it

**Comment by mdoutreluingne** [comment]
@kartikagarwal9, I tested having a js library to send mails, which is not at all secure but there is an old method in js which is the "mailto:", which calls for mail applications on your computer to send an email, I will the PR. Otherwise, keep my contact.php and index.php and I suggest you use  hosters like PlanetHoster or webhost to host your website and which supports php, a database and an email account to receive emails.
